version: '3'

services:
  lb-seduc-portal:
    restart: always
    container_name: 'lb-seduc-portal'
    hostname: 'lb-seduc-portal'
    domainname: educacao.seducdevel.ma.gov.br
    image: nginx:latest
    ports:
      - 8001:80
    volumes:
      - /etc/letsencrypt/archive/www.educacao.ma.gov.br-0001:/etc/nginx/certs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./vhost:/etc/nginx/conf.d
      - ./log:/var/log/nginx/
      - ./matricula:/usr/share/nginx/html
    environment:
      - VIRTUAL_HOST=www.educacao.ma.gov.br
      #- VIRTUAL_NETWORK=votacao-test

#networks:
#  default:
#    external:
#      name: votacao-test

# ADICIONAR O BASH AO CONTAINER QUE NÃO POSSUI
# docker-composer exec [nome_container] apk add bash